---
name: Continuous Integration

on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - develop

jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        os: [macos-15, ubuntu-24.04, windows-2022]

        # type: [shared, static]

        # include:
        #   - {type: shared, shared: YES}
        #   - {type: static, shared: NO}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install static analyzers
        if: matrix.os == 'macos-15'
        run: >-
          brew install llvm@18 cmake ninja

      - name: Install static analyzers
        if: matrix.os == 'ubuntu-24.04'
        run: >-
          sudo apt-get install clang-tidy-18 ninja-build -y -q

          sudo update-alternatives --install
          /usr/bin/clang-tidy clang-tidy
          /usr/bin/clang-tidy-18 140

      - name: Setup MultiToolTask
        if: matrix.os == 'windows-2022'
        run: |
          Add-Content "$env:GITHUB_ENV" 'UseMultiToolTask=true'
          Add-Content "$env:GITHUB_ENV" 'EnforceProcessCountAcrossBuilds=true'

      - name: Configure
        shell: pwsh
        run: cmake --preset=Debug # -D BUILD_SHARED_LIBS=${{ matrix.shared }}

      - name: Setup PATH
        if: matrix.os == 'windows-2022' && matrix.type == 'shared'
        run: Add-Content "$env:GITHUB_PATH" "$(Get-Location)\build\Debug"

      - name: Build
        run: cmake --build build --config Debug -j 2

      - name: Test
        working-directory: build
        run: ctest --output-on-failure --no-tests=error -C Debug -j 2

      - name: Install
        run: cmake --install build --config Debug --prefix prefix
